// This file was generated by prisma-field-encryption.

<<<<<<< HEAD
import type { PrismaClient, goals } from '../C:\Users\lenovo\Downloads\chetan\DevKo\node_modules\@prisma\client'
=======
import type { PrismaClient, goals } from '../D:\GHR-Hacks\DevKo\node_modules\@prisma\client'
>>>>>>> 677b9aab92592b5afc9beda5d3fcdb78d8d4fe53
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = goals['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'goals',
    client,
    getTotalCount: client.goals.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.goals.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        name: true,
        target_amount: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.goals.update({
      where: {
        id: record.id
      },
      data: {
        name: record.name,
        target_amount: record.target_amount
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "name": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "target_amount": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "user": {
 *       "modelName": "users",
 *       "isList": false
 *     }
 *   }
 * }
 */
